### ISSUE TITLE
Disable image default features

### ISSUE THREAD

**Issue by Skgland** [anshap1719/image-hdr#4]
Currently `image-hdr` includes `image` as a dependency without disabling default features.
As a result `image` pulls in a lot of dependencies for most/all image formats that it supports.
It would be good if `image-hdr` could set `default-features = false` for `image` so that one can enable only those formats one needs.

~~It looks like that might have been intended as in `Cargo.toml` the `jpeg` feature is explicitly enabled when `image` is used as a dev-dependency even though it is already implied by the normal dependency declaration.~~

<details>

```toml
[dependencies]
image = "0.25.2"

[dev-dependencies]
image = { version = "0.25.2", features = ["jpeg"] }
```
</details>

Edit: I added that in #3
